

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8766

spring:
  application:
    name: eshop-datasync-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    platform: mysql
    url: jdbc:mysql://localhost:3306/eshop?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
